"""initial migration

Revision ID: 004871f78ac3
Revises: 4acfd40a964f
Create Date: 2019-09-26 18:13:27.380793

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004871f78ac3'
down_revision = '4acfd40a964f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'downloads')
    # ### end Alembic commands ###
