"""initial migration

Revision ID: 007a11f20cfc
Revises: 74afcbf9181a
Create Date: 2019-09-29 15:58:30.992956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '007a11f20cfc'
down_revision = '74afcbf9181a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('cover', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'cover')
    # ### end Alembic commands ###
