"""initial migration

Revision ID: 0aa8005d666f
Revises: 7c49e7512bef
Create Date: 2019-10-30 20:10:02.193030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa8005d666f'
down_revision = '7c49e7512bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('receveur', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comment', 'receveur')
    # ### end Alembic commands ###
