"""initial migration

Revision ID: 0d70d788deca
Revises: 9239997e47f6
Create Date: 2019-10-22 00:33:12.826966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d70d788deca'
down_revision = '9239997e47f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ebook', sa.Column('date_posted', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ebook', 'date_posted')
    # ### end Alembic commands ###
