"""initial migration

Revision ID: 1846dd90fac3
Revises: d8cbcfb636e6
Create Date: 2019-09-27 10:23:28.632479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1846dd90fac3'
down_revision = 'd8cbcfb636e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('_downloads', sa.Integer(), nullable=True))
    op.drop_column('file', 'downloads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', '_downloads')
    # ### end Alembic commands ###
