"""initial migration

Revision ID: 21769ea6486c
Revises: ebd87b02f0a4
Create Date: 2019-09-27 09:59:52.173023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21769ea6486c'
down_revision = 'ebd87b02f0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('download', sa.Integer(), nullable=True))
    op.drop_column('file', 'downloads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', 'download')
    # ### end Alembic commands ###
