"""initial migrarate

Revision ID: 32602cf1208f
Revises: 6fd35edb4353
Create Date: 2019-11-30 23:19:59.593555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32602cf1208f'
down_revision = '6fd35edb4353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('nbrep', sa.Integer(), nullable=True))
    op.drop_column('comment', 'receveur')
    op.drop_constraint('reply_post_id_fkey', 'reply', type_='foreignkey')
    op.drop_column('reply', 'post_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('reply_post_id_fkey', 'reply', 'post', ['post_id'], ['id'])
    op.add_column('comment', sa.Column('receveur', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('comment', 'nbrep')
    # ### end Alembic commands ###
