"""initiate migration

Revision ID: 336eeee3b1eb
Revises: 
Create Date: 2020-01-04 15:11:14.953170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336eeee3b1eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('post', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.alter_column('file', 'category',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
