"""initial migration

Revision ID: 33fad4f8c718
Revises: 47d1f82d6b77
Create Date: 2019-10-17 19:39:05.364373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33fad4f8c718'
down_revision = '47d1f82d6b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.Integer(), nullable=False))
    op.add_column('post', sa.Column('unlikes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'unlikes')
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###
