"""initiate migration

Revision ID: 37ea7a6bc487
Revises: 336eeee3b1eb
Create Date: 2020-01-05 05:07:40.824449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ea7a6bc487'
down_revision = '336eeee3b1eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('books', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'books')
    # ### end Alembic commands ###
