"""initial migration

Revision ID: 3d6e28eb8294
Revises: 8b621db96e45
Create Date: 2019-10-31 09:13:09.053434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6e28eb8294'
down_revision = '8b621db96e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_date_posted'), 'post', ['date_posted'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_date_posted'), table_name='post')
    # ### end Alembic commands ###
