"""initial migrate

Revision ID: 41a6bce9d51a
Revises: b24f5e643728
Create Date: 2019-11-24 19:29:41.434544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41a6bce9d51a'
down_revision = 'b24f5e643728'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'reads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reads', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
