"""initial migration

Revision ID: 43cc5d7bbbbf
Revises: 21769ea6486c
Create Date: 2019-09-27 10:01:51.641887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43cc5d7bbbbf'
down_revision = '21769ea6486c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('_downloads', sa.Integer(), nullable=True))
    op.drop_column('file', 'download')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('download', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', '_downloads')
    # ### end Alembic commands ###
