"""initial migration

Revision ID: 4c50e8d0f2ba
Revises: b2256fd48f44
Create Date: 2019-09-28 00:02:44.840076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c50e8d0f2ba'
down_revision = 'b2256fd48f44'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'interests')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('interests', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
