"""initial migration

Revision ID: 4cb6b0654ddc
Revises: aef0ad1adf3d
Create Date: 2019-09-20 06:13:58.886132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb6b0654ddc'
down_revision = 'aef0ad1adf3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('description', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('file', 'description')
    # ### end Alembic commands ###
