"""initiate migrate

Revision ID: 5a86bfa92b30
Revises: 37ea7a6bc487
Create Date: 2020-01-08 06:20:49.485416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a86bfa92b30'
down_revision = '37ea7a6bc487'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'nbrlikes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'nbrlikes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
