"""initial migration

Revision ID: 684545a5d728
Revises: a45827f79f87
Create Date: 2019-09-18 10:33:15.628389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '684545a5d728'
down_revision = 'a45827f79f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'reads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reads', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
