"""initial migration

Revision ID: 6c041f0e2b04
Revises: 004871f78ac3
Create Date: 2019-09-27 03:57:33.010660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c041f0e2b04'
down_revision = '004871f78ac3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('_downloads', sa.Integer(), nullable=True))
    op.drop_column('file', 'downloads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', '_downloads')
    # ### end Alembic commands ###
