"""initial migrate

Revision ID: 6fd35edb4353
Revises: 9ebfda63278b
Create Date: 2019-11-25 16:59:41.185674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fd35edb4353'
down_revision = '9ebfda63278b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('publisher', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'publisher')
    # ### end Alembic commands ###
