"""initial migrate

Revision ID: 710e3fb4e64a
Revises: 91dbc0853b13
Create Date: 2019-11-24 03:23:27.374289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710e3fb4e64a'
down_revision = '91dbc0853b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_tags',
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], name='post_tags_post_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name='post_tags_tag_id_fkey')
    )
    # ### end Alembic commands ###
