"""initial migration

Revision ID: 74afcbf9181a
Revises: c226d45cb313
Create Date: 2019-09-28 00:37:13.872283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74afcbf9181a'
down_revision = 'c226d45cb313'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('nbcomments', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'nbcomments')
    # ### end Alembic commands ###
