"""initial migration

Revision ID: 7c49e7512bef
Revises: 53ac27eb3755
Create Date: 2019-10-30 19:45:27.239318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c49e7512bef'
down_revision = '53ac27eb3755'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply', sa.Column('post_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'reply', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reply', type_='foreignkey')
    op.drop_column('reply', 'post_id')
    # ### end Alembic commands ###
