"""initial migrate

Revision ID: 8a490d82490d
Revises: e463f451b07e
Create Date: 2019-11-24 19:10:20.269338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a490d82490d'
down_revision = 'e463f451b07e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('_reads', sa.Integer(), nullable=True))
    op.drop_column('post', 'reads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reads', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('post', '_reads')
    # ### end Alembic commands ###
