"""initial migration

Revision ID: 8b621db96e45
Revises: 0aa8005d666f
Create Date: 2019-10-31 08:56:19.545292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b621db96e45'
down_revision = '0aa8005d666f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'member_since')
    op.drop_column('user', 'last_seen')
    # ### end Alembic commands ###
