"""initial migration

Revision ID: 8e45405dbadf
Revises: d82c7bc40025
Create Date: 2019-10-20 06:36:09.207768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e45405dbadf'
down_revision = 'd82c7bc40025'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('nbrlikes', sa.Integer(), nullable=True))
    op.drop_column('post', 'unlikes')
    op.drop_column('post', 'likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('unlikes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('post', 'nbrlikes')
    op.drop_table('post_like')
    # ### end Alembic commands ###
