"""initial migration

Revision ID: 9239997e47f6
Revises: 8e45405dbadf
Create Date: 2019-10-21 02:26:51.448747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9239997e47f6'
down_revision = '8e45405dbadf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ebook',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=40), nullable=False),
    sa.Column('author', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('post_like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post_like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_like', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post_like', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('ebook')
    # ### end Alembic commands ###
