"""initial migration

Revision ID: b2256fd48f44
Revises: c43efbbece0d
Create Date: 2019-09-27 17:50:14.556401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2256fd48f44'
down_revision = 'c43efbbece0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloads', sa.Integer(), nullable=True))
    op.drop_column('file', '_downloads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('_downloads', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', 'downloads')
    # ### end Alembic commands ###
