"""initial migrate

Revision ID: b24f5e643728
Revises: aff060bb950b
Create Date: 2019-11-24 19:28:27.214356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24f5e643728'
down_revision = 'aff060bb950b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('reads', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'reads')
    # ### end Alembic commands ###
