"""initial migration

Revision ID: c226d45cb313
Revises: 4c50e8d0f2ba
Create Date: 2019-09-28 00:21:29.221729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c226d45cb313'
down_revision = '4c50e8d0f2ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloaded', sa.Integer(), nullable=True))
    op.drop_column('file', 'downloads')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloads', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', 'downloaded')
    # ### end Alembic commands ###
