"""initial migration

Revision ID: c43efbbece0d
Revises: dec80f6bd043
Create Date: 2019-09-27 17:46:56.778994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c43efbbece0d'
down_revision = 'dec80f6bd043'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('_downloads', sa.Integer(), nullable=True))
    op.drop_column('file', 'downloaded')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('downloaded', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('file', '_downloads')
    # ### end Alembic commands ###
