"""initial migrate

Revision ID: c4b4d3a4f082
Revises: 6671e5cac845
Create Date: 2019-11-05 22:24:30.591936

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4b4d3a4f082'
down_revision = '6671e5cac845'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cover',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.LargeBinary(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('file', 'cover')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('cover', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_table('cover')
    # ### end Alembic commands ###
