"""initial migration

Revision ID: d82c7bc40025
Revises: 33fad4f8c718
Create Date: 2019-10-17 19:40:38.659828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82c7bc40025'
down_revision = '33fad4f8c718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'likes',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('post', 'unlikes',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'unlikes',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('post', 'likes',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
